# Generated by Django 3.2 on 2021-05-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_name',)},
        ),
    ]
